server:
  port: 8771
spring:
  application:
    name: service-a-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #熔断超时时间
      timeout:
        enabled: false #超时发生异常属性关闭